name: Lint and Prettier

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.0'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Commit changes (if any)
        run: |
          git config --global user.name "Sathishramesh1"
          git config --global user.email "sathishrameshkec@gmail.com"  
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-format code with Prettier [skip ci]"
          git push https://Sathishramesh1:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Sathishramesh1/your-repo.git
